

from typing import List


DEFAULT_BOT_DETECTION_METHODS = []

DEFAULT_BOT_DETECTION_MAX_RETRIES: int = 5

DEFAULT_BOT_DETECTION_RETRY_WAIT_TIME: int = 30 # Seconds

DEFAULT_BOT_DETECTION_WAIT_FOR_PRESENCE_DELAY: int = 1.5 # Seconds